export const AUDIO = {
  PLAYLIST_UPDATED: 'PLAYLIST_UPDATED',
  RUN_SONG: 'RUN_SONG',
  DECODE: 'DECODE',
  DECODED_BUFFER: 'DECODED_BUFFER',
  PLAY: 'PLAY',
  STOP: 'STOP',
  SET_ANALYSER: 'SET_ANALYSER',
  AUDIO_IN_PROGRESS: 'AUDIO_IN_PROGRESS'
}
