export const AUDIO = {
  PLAYLIST_UPDATED: 'PLAYLIST_UPDATED',
  PLAY: 'PLAY',
  STOP: 'STOP',
  CHANGE_SONG: 'CHANGE_SONG',
  AUDIO_IN_PROGRESS: 'AUDIO_IN_PROGRESS',
  PROGRESS_UPDATED: 'PROGRESS_UPDATED'
}
