export const AUDIO = {
  PLAYLIST_UPDATED: 'PLAYLIST_UPDATED',
  DECODE: 'DECODE',
  DECODED_BUFFER: 'DECODED_BUFFER',
  PLAY: 'PLAY',
  STOP: 'STOP',
  CHANGE_SONG: 'CHANGE_SONG',
  AUDIO_IN_PROGRESS: 'AUDIO_IN_PROGRESS'
}
